server:
  port: 8050

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: consumer_route # 当前路由的标识, 要求唯一
          uri: lb://cloud-consumer # 请求要转发到的地址
          order: 1 # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
              - Path=/consumer_route/** # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
              - StripPrefix=1 # 转发之前去掉1层路径
              - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 5
                  key-resolver: '#{@ipKeyResolver}'
  redis:
    host: 172.17.15.77
    port: 6379
